version: '3'

services:
  database:
    image: postgres:13.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  pgAdmin:
    image: dpage/pgadmin4:4.27
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80


  backend:
    image: scope/scope-backend
    restart: unless-stopped
    build:
      context: ./scope-backend
      dockerfile: Dockerfile
    volumes:
      - ./scope-backend/:/app
      - /app/node_modules
    ports:
      - ${APP_BACKEND_DEV_PORT}:${APP_BACKEND_DEV_PORT}
    environment:
      APP_NAME: ${APP_NAME}
      PORT: ${APP_BACKEND_DEV_PORT}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    image: scope/scope-frontend
    restart: unless-stopped
    build:
      context: ./scope-frontend
      dockerfile: Dockerfile
    volumes:
      - ./scope-frontend/:/app
      - /app/node_modules
    ports:
      - ${APP_FRONTEND_DEV_PORT}:${APP_FRONTEND_DEV_PORT}
    environment:
      VUE_APP_NAME: ${APP_NAME}
      VUE_APP_FRONTEND_DOMAIN: ${APP_FRONTEND_DOMAIN}
      VUE_APP_FRONTEND_DEV_PORT: ${APP_FRONTEND_DEV_PORT}
      VUE_APP_BACKEND_DOMAIN: ${APP_BACKEND_DOMAIN}
      VUE_APP_BACKEND_PORT: ${APP_BACKEND_DEV_PORT}
      

